clubes=('Corinthians', 'Palmeiras', 'Santos', 'Gremio', 'Cruzeiro', 'Flamengo', 'Vasco', 'Chapecoense', 'Atletico', 'Botafogo','Atletico-PR','Bahia', 'Coritiba', 'Avai', 'Ponte Preta', 'Atletico-GO')
print(f'Lista de times do Brasileirao: {clubes}')
print('-='*30)
print(f'Os 5 primeiros sao: {clubes[0:5]}')
print('-='*30)
print(f'Os 4 ultimos sao: {clubes[12:]}')
print('-='*30)
s=sorted(clubes)
print(f'TImes em ordem alfabetica: {s}')
print('-='*30)
print(f'O Chapecoense esta na {clubes.index("Chapecoense")+1}ª posiçao')